 name: Deploy to EC2

on:
  push:
    branches:
      - kritan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t username/repository:tag .
        docker push username/repository:tag

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > key.pem
        chmod 400 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
          docker pull username/repository:tag
          docker stop backend_container || true
          docker rm backend_container || true
          docker run -d -p 8000:8000 --name backend_container username/repository:tag
        EOF
